### PR TITLE
[Deps] update eslint-module-utils

### LINKED ISSUE #2255: Cannot find module eslint-module-utils/visit after updating to v2.25.1
I had previously `eslint-plugin-import@2.24.2`. When updating to `v2.25.1`, I'm getting the following error:

```

Syntax Error: Thread Loader (Worker 0)
Failed to load plugin 'import' declared in '.eslintrc.json': Cannot find module 'eslint-module-utils/visit'
Require stack:
- /code/node_modules/eslint-plugin-import/lib/ExportMap.js
- /code/node_modules/eslint-plugin-import/lib/rules/named.js
- /code/node_modules/eslint-plugin-import/lib/index.js
- /code/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /code/node_modules/@eslint/eslintrc/lib/index.js
- /code/node_modules/eslint/lib/cli-engine/cli-engine.js
- /code/node_modules/eslint/lib/cli-engine/index.js
- /code/node_modules/eslint/lib/api.js
- /code/node_modules/eslint-loader/index.js
- /code/node_modules/loader-runner/lib/loadLoader.js
- /code/node_modules/loader-runner/lib/LoaderRunner.js
- /code/node_modules/thread-loader/dist/worker.js
```

### PR DESCRIPTION
**Pull request by slaweet**
Resolves #2255

 ## What was the problem?
 the file eslint-module-utils/visit didn't exist previously
 https://github.com/import-js/eslint-plugin-import/tree/v2.24.2/utils/visit.js
 it only exists in the latest minor version bump
 https://github.com/import-js/eslint-plugin-import/blob/v2.25.0/utils/visit.js

### CODE REVIEW

**Comment by paescuj** [comment]
@slaweet Huh, strange... Maybe this is prevented by a global setting in your account. However, IMO this check can be ignored - but that's up to the maintainers...

**Comment by slaweet** [comment]
> @slaweet the issue is that you made a PR from a fork you don't own. Please never do that.

@ljharb Opening PRs from my company Github organization is our guideline for contributing to open source in work hours. So far nobody complained about extra refs being a problem (Even when contributing to much bigger repo, such as https://github.com/DefinitelyTyped/DefinitelyTyped). 

> Since PRs once opened permanently pollute a repo, I will not release a fix for this until I can force push to this PR, so this PR now blocks the release.

I see you already released the patch (Good call, given we're in two very different time zones), so closing this PR.
