### ISSUE TITLE
Cannot find module eslint-module-utils/visit after updating to v2.25.1

### ISSUE THREAD

**Issue by slaweet** [benmosher/eslint-plugin-import#2255]
I had previously `eslint-plugin-import@2.24.2`. When updating to `v2.25.1`, I'm getting the following error:

```

Syntax Error: Thread Loader (Worker 0)
Failed to load plugin 'import' declared in '.eslintrc.json': Cannot find module 'eslint-module-utils/visit'
Require stack:
- /code/node_modules/eslint-plugin-import/lib/ExportMap.js
- /code/node_modules/eslint-plugin-import/lib/rules/named.js
- /code/node_modules/eslint-plugin-import/lib/index.js
- /code/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /code/node_modules/@eslint/eslintrc/lib/index.js
- /code/node_modules/eslint/lib/cli-engine/cli-engine.js
- /code/node_modules/eslint/lib/cli-engine/index.js
- /code/node_modules/eslint/lib/api.js
- /code/node_modules/eslint-loader/index.js
- /code/node_modules/loader-runner/lib/loadLoader.js
- /code/node_modules/loader-runner/lib/LoaderRunner.js
- /code/node_modules/thread-loader/dist/worker.js
```

**Comment by Haprog** [comment]
I have the same problem. See details in this PR that only bumps this dependency and causes eslint to fail in the CI build https://github.com/Haprog/hash-actions/pull/47

**Comment by ljharb** [comment]
I would expect anyone who runs `npm install --save-dev eslint-plugin-import` or `yarn add -D eslint-plugin-import` to get the latest version of all the subdeps; if this isn't the case, in yarn you can `yarn upgrade eslint-module-utils`, and i'm sure there's a similar command for npm.

**Comment by ljharb** [comment]
Yes, there’s two open PRs already to do that. I’m waiting on something from one of them, and then I’ll cut a patch release.

In the meantime, it’s trivial for anyone to fix this by upgrading eslint-module-utils in their lockfile.

**Comment by smlabt** [comment]
> Yes, there’s two open PRs already to do that. I’m waiting on something from one of them, and then I’ll cut a patch release.
> 
> In the meantime, it’s trivial for anyone to fix this by upgrading eslint-module-utils in their lockfile.

I have updated `^2.6.2` to `~2.7.0`, so I think 2.6.2 won't be valid in any lockfile now. I think the problem with `^2.7.0` is that `2.6.2` is still a valid version.

**Comment by ljharb** [comment]
@smlabt i won't land anything not using `^2.7.0`; and no, `^2.7.0` is not satisfied by anything less than v2.7.0.
